name: stackedql_ferry
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ">=2.15.0-42.0.dev <3.0.0"

dependencies:
  ferry: ^0.10.4
  ferry_hive_store: ^0.4.4
  gql_error_link: ^0.2.0
  gql_http_link: ^0.4.0
  gql_transform_link: ^0.2.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0

dev_dependencies:
  build_runner: ^2.1.2
  ferry_generator: ^0.4.4
  lints: ^1.0.0
  test: ^1.16.0
